language: cpp
before install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libtag1-dev libmagic-dev libboost-filesystem-dev libboost-program-options-dev libboost-system-dev libboost-regex-dev
script: 'cmake . && cmake --build . && cmake --build . --target test'
notifications:
  recipients:
    - kaethorn@gmail.com
