language: cpp
install:
  - sudo apt-get install -y libtag1-dev
  - sudo apt-get install -y libmagic-dev
  - sudo apt-get install -y libboost-filesystem-dev
  - sudo apt-get install -y libboost-program-options-dev
  - sudo apt-get install -y libboost-system-dev
  - sudo apt-get install -y libboost-regex-dev
script: 'cmake . && cmake --build . && cmake --build . --target test'
notifications:
  recipients:
    - kaethorn@gmail.com
